run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused

issues:
  exclude-dirs:
    - internal/generated
