# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: 2

project_name: nvfleetctl
dist: dist/macos

builds:
  - id: nvfleetctl-macos
    main: ./cmd/nvfleetctl
    binary: "nvfleetctl_{{ .Arch }}"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.buildDate={{ .CommitDate }}
