#!/usr/bin/env bash

# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

if [[ $# -ne 3 ]]; then
  echo "Usage: $0 <version> <archive-directory> <output-directory>" >&2
  exit 1
fi

for command in codesign unzip xcrun; do
  command -v "$command" >/dev/null 2>&1 || {
    echo "Required command not found: $command" >&2
    exit 1
  }
done

version="${1#v}"
input_dir="$(cd "$2" && pwd)"
output_dir="$(mkdir -p "$3" && cd "$3" && pwd)"
profile="${APPLE_NOTARY_PROFILE:-fleetint-notarytool}"
team_id="${APPLE_TEAM_ID:-6KR3T733EC}"
work_dir="$(mktemp -d "${TMPDIR:-/tmp}/nvfleetint-notarize.XXXXXX")"

cleanup() {
  case "$work_dir" in
    "${TMPDIR:-/tmp}"/nvfleetint-notarize.*) rm -rf "$work_dir" ;;
    *) echo "Refusing to remove unexpected temporary directory: $work_dir" >&2 ;;
  esac
}
trap cleanup EXIT

if [[ -n "${APPLE_ID:-}" || -n "${APPLE_APP_SPECIFIC_PASSWORD:-}" ]]; then
  : "${APPLE_ID:?APPLE_ID is required}"
  : "${APPLE_APP_SPECIFIC_PASSWORD:?APPLE_APP_SPECIFIC_PASSWORD is required}"
  xcrun notarytool store-credentials "$profile" \
    --apple-id "$APPLE_ID" \
    --password "$APPLE_APP_SPECIFIC_PASSWORD" \
    --team-id "$team_id"
fi

for arch in amd64 arm64; do
  archive_name="nvfleetint_${version}_darwin_${arch}.zip"
  input="$input_dir/$archive_name"
  output="$output_dir/$archive_name"
  extract_dir="$work_dir/$arch"

  [[ -f "$input" ]] || { echo "macOS archive not found: $input" >&2; exit 1; }
  mkdir -p "$extract_dir"
  unzip -q "$input" -d "$extract_dir"
  [[ -f "$extract_dir/nvfleetint" ]] || {
    echo "nvfleetint was not found in $archive_name" >&2
    exit 1
  }
  codesign --verify --strict --verbose=4 "$extract_dir/nvfleetint"

  # Notarization does not modify a ZIP. Submit and publish these exact bytes so
  # the checksum generated by GoReleaser remains valid.
  cp "$input" "$output"
  xcrun notarytool submit "$output" \
    --keychain-profile "$profile" \
    --wait \
    --progress

  # Apple creates an online ticket for the executable inside the ZIP. Tickets
  # cannot be stapled to a ZIP or a standalone command-line executable.
  codesign -vvvv -R="notarized" --check-notarization "$extract_dir/nvfleetint"
done

echo "Apple accepted both macOS archives in $output_dir"
